config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'

  ### OBS-Start
  # on_publish
  post 'on_publish' => 'stream#on_publish'

  # on_play
  post 'on_play' => 'stream#on_play'

  # on_record_done
  post 'on_record_done' => 'stream#on_record_done'

  # screenshot_done
  post 'screenshot_done' => 'stream#screenshot_done'
  ### OBS-End

  # Streams
  get 'streams' => 'stream#all'

  # Stream-User
  get ':nickname' => 'stream#user', as: :stream

  # Stream-Current
  post ':nickname/current' => 'stream#current'

  # Stream-Chat
  get ':nickname/chat_window' => 'stream#extract_chat', as: :extract_chat
  post ':nickname/chat' => 'stream#chat', as: :chat

  # User-Update-Description
  post ':nickname/update_description' => 'users#update_description', as: :update_description

  # User-Update-Title
  post ':nickname/update_title' => 'users#update_title', as: :update_title
  post 'profile/update' => 'users#update'
  post 'profile/category' => 'users#category'

  # User-Update-Record-Title
  post ':nickname/record/:uuid/update_title' => 'users#update_record_title', as: :update_record_title

  # User-Profile
  get ':nickname/profile' => 'users#profile', as: :profile

  # User-Play-Record
  get ':nickname/record/:uuid' => 'records#play', as: :play_record

  # User-Private-Stream
  get ':uuid/stream' => 'users#private_stream', as: :private_stream

  # User-Stop-Private-Stream
  get ':uuid/stop_stream' => 'users#stop_private_stream', as: :stop_private_stream

  # Record-Category
  post ':nickname/record/:uuid/category' => 'users#record_category'

  # Channel - Block
  resource :channel, only: [] do
    member do
      post :block
      post :unblock
    end
  end

  # Follow
  get ':nickname/follow' => 'users#follow', as: :follow

  # Unfollow
  get ':nickname/unfollow' => 'users#unfollow', as: :unfollow

  # Group
  post ':nickname/groups' => 'groups#create'

  # Group-Invite
  get '/groups/:uuid/invite/:user_uuid' => 'groups#invite', as: :group_invite

  # API
  namespace :api, format: :json do
    namespace :v1 do
      get 'me' => 'users#me'

      scope :videos do
        get '' => 'videos#all'
        get '/' => 'videos#all'
        get '/:nickname' => 'videos#user'
        get '/:nickname/:uuid' => 'videos#video'
        patch '/:nickname/:uuid/title' => 'videos#update'
        patch '/:nickname/:uuid/category' => 'videos#update'
      end

      scope :streams do
        get '' => 'streams#all'
        get '/:nickname' => 'streams#user'
        patch '/:nickname/title' => 'streams#update'
        get '/:nickname/comments' => 'streams#comments'
        # post '/:nickname/comments' => 'streams#create_comment'
        # get '/:nickname/block_list' => 'streams#block_list'
        # post '/:nickname/block' => 'streams#block'
        # post '/:nickname/unblock' => 'streams#unblock'
      end

      get '/:nickname/followings' => 'users#followings'
      get '/:nickname/followers' => 'users#followers'
    end
  end

  get '*path' => redirect('/')
end

app/models/record.rb
# == Schema Information
#
# Table name: records
#
#  id              :integer          not null, primary key
#  video_path      :string
#  screenshot_path :string
#  uuid            :string
#  uploaded        :boolean
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  title           :string
#  duration        :float
#  total           :integer
#  category        :integer
#  private         :boolean
#  group_id        :integer
#

# Record
class Record < ActiveRecord::Base
  include Contracts::Core
  include Contracts::Builtin

  validates :user_id, presence: true
  belongs_to :user
  belongs_to :group

  before_create do
    self.duration = 1.0
    self.category = self.user.category
    self.uuid = ((0..9).to_a.sample(3) + ('a'..'z').to_a.sample(3)).shuffle.join
  end

  def public_attributes_with_thumbnail
    {
      uuid: uuid,
      title: title,
      play_url: video_url,
      thumbnail: screenshot_url,
      duration: duration,
      pv: total,
      category: category_in_text,
      user: user.basic_info
    }
  end

  Contract None => String
  def screenshot_url
    return "/#{uuid}.png" unless uploaded?
    s3 = AWS::S3.new
    bucket = s3.buckets['live-streaming-staging']
    bucket.acl = :public_read
    obj = bucket.objects[screenshot_path.to_s]
    # obj.acl = :public_read
    obj.public_url.to_param
  end

  Contract None => String
  def video_url
    return "/#{uuid}.mp4" unless uploaded?
    s3 = AWS::S3.new
    bucket = s3.buckets['live-streaming-staging']
    bucket.acl = :public_read
    obj = bucket.objects[video_path.to_s]
    # obj.acl = :public_read
    obj.public_url.to_param
  end

  def copy_screenshot_to_tmp(input_flv_path)
    flv = FFMPEG::Movie.new("/usr/local/nginx/html/hls/#{user.nickname}.flv")
    screenshot_path = "/usr/local/nginx/html/screenshot/#{user.nickname}.png"
    begin
      File.copy_stream(screenshot_path, "public/#{uuid}.png")
    rescue
      puts "File does not exist on #{screenshot_path}"
    end
    update(screenshot_path: "public/#{uuid}.png", duration: flv.duration)
  end

  def copy_video_to_tmp(input_flv_path)
    FFMPEG::Movie.new("/usr/local/nginx/html/hls/#{user.nickname}.flv").transcode("public/#{uuid}.mp4", '-vcodec copy -acodec copy') do |progress|
      puts progress
    end
    update(video_path: "public/#{uuid}.mp4")
  end

  def upload_to_s3(input_flv_path)
    flv = FFMPEG::Movie.new(input_flv_path)
    screenshot_path = "/usr/local/nginx/html/screenshot/#{user.nickname}.png"
    s3 = AWS::S3.new
    bucket = s3.buckets['live-streaming-staging']

    # Screenshot
    screenshot = bucket.objects["#{user.uuid}/screenshot/#{uuid}.png"]
    screenshot.write(File.open(screenshot_path))
    screenshot.acl = :public_read

    # Video
    video = bucket.objects["#{user.uuid}/records/#{uuid}.mp4"]
    video.write(File.open("public/#{uuid}.mp4"))
    video.acl = :public_read

    update(video_path: video.key, screenshot_path: screenshot.key, uploaded: true, duration: flv.duration)
    File.delete("/usr/local/nginx/html/hls/#{user.nickname}.flv")
    File.delete("/usr/local/nginx/html/screenshot/#{user.nickname}.png")
    File.delete("public/#{uuid}.png")
    File.delete("public/#{uuid}.mp4")
  rescue
    puts 'Error on app/models/record.rb'
  end

  Contract Num => String
  def category_in_text
    %w(UI/UX Ruby Python)[category]
  end
end

app/controllers/records_controller.rb
# == Schema Information
#
# Table name: records
#
#  id              :integer          not null, primary key
#  video_path      :string
#  screenshot_path :string
#  uuid            :string
#  uploaded        :boolean
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  title           :string
#  duration        :float
#  total           :integer
#  category        :integer
#  private         :boolean
#  group_id        :integer
#

class RecordsController < ApplicationController
  rescue_from Exception, with: :respond_with_500

  def play
    @user = User.find_by(nickname: params[:nickname])
    @record = @user.records.find_by(uuid: params[:uuid])
    total = @record.total
    total += 1
    @record.update(total: total)
    @record.reload
  end

  private

  def respond_with_500
    return redirect_to stream_path(nickname: @user.nickname) if @user.present?
    redirect_to root_path
  end
end

app/views/records/_all.html.erb
<% if records.count == 0 %>
  <span class="subtitle"><%= t('user.zero_records') %></span>
<% end %>
<% records.reverse.each_slice(4) do |record| %>
  <div class="columns">
    <% unless record[0].nil? %>
      <%= render partial: 'records/record', locals: { record: record[0], user: record[0].user } %>
    <% end %>
    <% unless record[1].nil? %>
      <%= render partial: 'records/record', locals: { record: record[1], user: record[1].user } %>
    <% end %>
    <% unless record[2].nil? %>
      <%= render partial: 'records/record', locals: { record: record[2], user: record[2].user } %>
    <% end %>
    <% unless record[3].nil? %>
      <%= render partial: 'records/record', locals: { record: record[3], user: record[3].user } %>
    <% end %>
  </div>
<% end %>

app/views/records/_player.html.erb
<video id="my-video" class="video-js" autoplay controls preload="auto" height="auto" width="100%" data-setup="{}">
  <source src="<%= @record.video_url %>" type="video/mp4" />
  <p class="vjs-no-js">
   To view this video please enable JavaScript, and consider upgrading to a web browser that
   <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
  </p>
</video>
<script src="http://vjs.zencdn.net/5.9.2/video.js"></script>

app/views/records/_record.html.erb
<%= stylesheet_link_tag 'records' %>
<div class="column is-3">
  <%= link_to play_record_path(nickname: user.nickname, uuid: record.uuid), target: '_blank' do %>
    <div class="card">
      <div class="card-image">
        <figure class="image is-4by3"><%= image_tag asset_path('loading.gif'), alt: record.uuid, class: "video-uuid #{record.uuid} init", uid: record.uuid, owner: user.nickname %></figure>
        <% unless record.uploaded? %>
          <span class="tag is-danger"><%= t('streaming.making') %></span>
        <% else %>
          <span class="tag is-dark"><%= category(record.category) %></span>
        <% end %>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-32x32">
              <%= image_tag "#{user.gh.image || user.twitter_image_url}", alt: user.name %>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-5"><%= user.name %></p>
            <p class="subtitle is-6">@<%= "#{user.nickname}" %></p>
          </div>
        </div>
        <div class="content">
          <p class="subtitle is-5"><%= "#{record.title || I18n.t('content.title.default')}" %></p>
          <small><%= time(record.duration.ceil) %></small><br />
          <small><%= t('streaming.total') %> : <%= record.total || 0 %></small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/records/play.html.erb
<%= stylesheet_link_tag 'records' %>

<!-- Main -->
<div id="record_main" class="container">
  <div class="columns">
    <div class="column is-8">
      <article class="media">
        <figure class="media-left">
          <p class="image is-64x64">
            <%= image_tag @user.gh.image, alt: @user.name %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <% if current_user == @user %>
              <div id="stream_title">
              <span data-balloon="タイトルをクリックして編集できます" data-balloon-pos="up" style="font-size:18pt;"><%= @record.title || I18n.t('content.title.default') %></span><br />
              </div>
              <form class="title_form" format="js" accept-charset="UTF-8" data-remote="true" method="post" action="/<%= @user.nickname %>/record/<%= @record.uuid %>/update_title" style="display:none;height:34px;">
                <input type="text" name="record[title]" class="input update_title" value="<%= @record.title %>" focus="true" placeholder="Enterで保存" />
              </form>
            <% else %>
              <div>
                <span id="stream_title"><%= @record.title || I18n.t('content.title.default') %></span>
              </div>
            <% end %>
            <span id="username"><%= @user.name %></span>
            <span class=" category tag is-dark"><%= category(@record.category) %></span>
          </div>
        </div>
      </article>
      <%= render partial: 'player', locals: { record: @record } %>
      <p id="status">
        <span class="subtitle"><strong><%= t('streaming.total') %>  <%= @record.total %></strong></span>
        <% if user_signed_in? %>
          <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
              <%= button_tag t('user.unfollow'), class: 'button is-danger unfollow', style: 'float:right;' %>
              <%= button_tag t('user.follow'), class: 'button is-success follow', style: 'float:right;display:none;' %>
            <% else %>
              <%= button_tag t('user.follow'), class: 'button is-success follow', style: 'float:right;' %>
              <%= button_tag t('user.unfollow'),  class: 'button is-danger unfollow', style: 'float:right;display:none;' %>
            <% end %>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
</div>

<!-- Reocrds -->
<div class="container">
  <%= render partial: 'all', locals: { records: @user.records.select { |r| r.duration.ceil > 0 } } %>
</div>
<%= javascript_include_tag 'stream' %>
<script>
  $(function() {
    var update = function() {
      toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-center",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "300",
        "timeOut": "1000",
        "extendedTimeOut": "300",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
      }
      toastr.success('更新しました')
    }

    $('form').submit(function() {
      update();
      $('#stream_title').show();
      $('#stream_title').html('<span data-balloon="タイトルをクリックして編集できます" data-balloon-pos="up" style="font-size:18pt;">' + $('.update_title').val() + '</span><br />');
      $('.title_form').hide();
      $('.update_title').focusout();
      return true;
    });

    $('.follow').click(function(e) {
      e.preventDefault();
      $.ajax({
        type: 'GET',
        url: "/<%= @user.nickname %>/follow",
        success: function() {
          $('.follow').hide();
          $('.unfollow').show();
        }
      });
    });
    $('.unfollow').click(function(e) {
      e.preventDefault();
      $.ajax({
        type: 'GET',
        url: "/<%= @user.nickname %>/unfollow",
        success: function() {
          $('.unfollow').hide();
          $('.follow').show();
        }
      });
    });
    $('#stream_title').click(function() {
      $(this).hide()
      $('.title_form').show();
      $('.update_title').focus();
    });
    $('.update_title').focusout(function() {
      $('.title_form').hide();
      $('#stream_title').show();
    });
  });
</script>