config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'

  ### OBS-Start
  # on_publish
  post 'on_publish' => 'stream#on_publish'

  # on_play
  post 'on_play' => 'stream#on_play'

  # on_record_done
  post 'on_record_done' => 'stream#on_record_done'

  # screenshot_done
  post 'screenshot_done' => 'stream#screenshot_done'
  ### OBS-End

  # Streams
  get 'streams' => 'stream#all'

  # Stream-User
  get ':nickname' => 'stream#user', as: :stream

  # Stream-Current
  post ':nickname/current' => 'stream#current'

  # Stream-Chat
  get ':nickname/chat_window' => 'stream#extract_chat', as: :extract_chat
  post ':nickname/chat' => 'stream#chat', as: :chat

  # User-Update-Description
  post ':nickname/update_description' => 'users#update_description', as: :update_description

  # User-Update-Title
  post ':nickname/update_title' => 'users#update_title', as: :update_title
  post 'profile/update' => 'users#update'
  post 'profile/category' => 'users#category'

  # User-Update-Record-Title
  post ':nickname/record/:uuid/update_title' => 'users#update_record_title', as: :update_record_title

  # User-Profile
  get ':nickname/profile' => 'users#profile', as: :profile

  # User-Play-Record
  get ':nickname/record/:uuid' => 'records#play', as: :play_record

  # User-Private-Stream
  get ':uuid/stream' => 'users#private_stream', as: :private_stream

  # User-Stop-Private-Stream
  get ':uuid/stop_stream' => 'users#stop_private_stream', as: :stop_private_stream

  # Record-Category
  post ':nickname/record/:uuid/category' => 'users#record_category'

  # Channel - Block
  resource :channel, only: [] do
    member do
      post :block
      post :unblock
    end
  end

  # Follow
  get ':nickname/follow' => 'users#follow', as: :follow

  # Unfollow
  get ':nickname/unfollow' => 'users#unfollow', as: :unfollow

  # Group
  post ':nickname/groups' => 'groups#create'

  # Group-Invite
  get '/groups/:uuid/invite/:user_uuid' => 'groups#invite', as: :group_invite

  # API
  namespace :api, format: :json do
    namespace :v1 do
      get 'me' => 'users#me'

      scope :videos do
        get '' => 'videos#all'
        get '/' => 'videos#all'
        get '/:nickname' => 'videos#user'
        get '/:nickname/:uuid' => 'videos#video'
        patch '/:nickname/:uuid/title' => 'videos#update'
        patch '/:nickname/:uuid/category' => 'videos#update'
      end

      scope :streams do
        get '' => 'streams#all'
        get '/:nickname' => 'streams#user'
        patch '/:nickname/title' => 'streams#update'
        get '/:nickname/comments' => 'streams#comments'
        # post '/:nickname/comments' => 'streams#create_comment'
        # get '/:nickname/block_list' => 'streams#block_list'
        # post '/:nickname/block' => 'streams#block'
        # post '/:nickname/unblock' => 'streams#unblock'
      end

      get '/:nickname/followings' => 'users#followings'
      get '/:nickname/followers' => 'users#followers'
    end
  end

  get '*path' => redirect('/')
end

app/controllers/api/v1/streams_controller.rb
module Api
  module V1
    class StreamsController < Api::V1::ApiController
      include Contracts::Core
      include Contracts::Builtin

      skip_before_action :doorkeeper_authorize!, only: [:all, :user, :comments]

      Contract None => ArrayOf[String]
      def all
        @users = User.where(live: true).map(&:public_attributes_with_thumbnail)
        render json: { streams: @users }
      end

      Contract Hash => ArrayOf[String]
      def user
        @user = User.find_by(user_params)
        render json: @user.public_attributes
      end

      def update
        @user = User.find_by(user_params)
        return render nothing: true, status: 200 if valid_user_from_api(params, @user) && @user.update(update_params)
        render nothing: true, status: 500
      rescue
        render nothing: true, status: 500
      end

      Contract Hash => ArrayOf[String]
      def comments
        @user = User.find_by(user_params)
        @chats = @user.chats.all.map(&:detail)
        render json: { comments: @chats }
      end

      private

      def valid_user_from_api(params, user)
        return false if params[:title].nil?
        return false if params[:current_user_nickname].nil?
        return false if user.nil?
        return false if user.default_nickname != params[:current_user_nickname]
        true
      end

      Contract Hash => Hash
      def user_params
        params.permit(:nickname)
      end

      Contract Hash => Hash
      def update_params
        params.permit(:title)
      end
    end
  end
end

app/controllers/stream_controller.rb
# Streaming
class StreamController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:on_record_done, :on_publish, :chat, :screenshot_done, :current, :on_play]

  def screenshot_done
    @user = User.find_by(nickname: params[:name])
    return render nothing: true, status: 200 unless @user.live?
    # screenshot_path = "/usr/local/nginx/html/screenshot/#{@user.nickname}.png"
    # if File.exist?(screenshot_path) && !File.exist?("tmp/#{@user.nickname}.png") && File.size(screenshot_path) > 0
      # puts 'thumbnail created'
      # File.copy_stream(screenshot_path, "tmp/#{@user.nickname}.png")
      # File.copy_stream(screenshot_path, "public/#{@user.uuid}_current.png")
    # else
      # File.exist?("tmp/#{@user.nickname}.png")
      # File.exist?("public/#{@user.uuid}_current.png")
    # end
    render nothing: true, status: 200
  end

  def extract_chat
    @user = User.find_by(nickname: params[:nickname])
    @url = ENV['URL']
    @client_token = ENV['CLIENT_TOKEN']
    @channel = @user.nickname
    @chats = @user.chats.all
    @chat = @user.chats.new
    render layout: false
  rescue
    redirect_to root_path
  end

  def current
    @user = User.find_by(nickname: params[:nickname])
    @pushould = Pushould.new(server_token: ENV['SERVER_TOKEN'],
                             url: ENV['URL'],
                             email: ENV['EMAIL'],
                             password: ENV['PASSWORD'])

    @pushould.trigger(room: @user.nickname,
                      event: 'check',
                      data: {})
    render nothing: true, status: 200
  rescue
    render nothing: true, status: 500
  end

  def chat
    @user = User.find_by(nickname: params[:nickname])
    @chat = @user.chats.create(sender: current_user.nickname, text: params['chat']['text'])
    @chats = @user.chats.all
    @pushould = Pushould.new(server_token: ENV['SERVER_TOKEN'],
                             url: ENV['URL'],
                             email: ENV['EMAIL'],
                             password: ENV['PASSWORD'])

    @sender = User.find_by(nickname: @chat.sender)
    @pushould.trigger(room: @user.nickname,
                      event: 'send',
                      data: {
                        name: "#{@sender.name}",
                        image: "#{@sender.gh.image}",
                        nickname: "#{@sender.nickname}",
                        text: "#{@chat.text}"
                      })
    render :chat, status: 200
  rescue
    render nothing: true, status: 500
  end

  def user
    @user = User.find_by(nickname: params[:nickname])
    # return render json: { status: 500 } if @user.private_stream? && !user_signed_in?
    return redirect_to root_path if @user.private? && !user_signed_in?
    @streaming_group = @user.groups.find_by(streaming: true)
    return redirect_to root_path if @user.private? && @streaming_group.users.exclude?(current_user)
    if @user.live?
      total = @user.total
      total += 1
      @user.update(total: total)
      @pushould = Pushould.new(server_token: ENV['SERVER_TOKEN'],
                               url: ENV['URL'],
                               email: ENV['EMAIL'],
                               password: ENV['PASSWORD'])

      @pushould.trigger(room: @user.nickname,
                        event: 'view',
                        data: {
                          views: total
                        })
    else
      if @user.records.count == 0
        @total = @user.total
      else
        @total = @user.total + @user.records.map(&:total).inject(:+)
      end
    end
    description = HTML::Pipeline::MarkdownFilter.new("#{@user.description || 'There is no description.'}")
    @content = description.call
    @url = ENV['URL']
    @client_token = ENV['CLIENT_TOKEN']
    @channel = @user.nickname
    @chats = @user.chats.all
    @chat = @user.chats.new
  rescue
    redirect_to root_path
  end

  def all
    @users = User.where(live: true)
  end

  def on_play
    # puts params[:addr]
    # puts request.remote_ip
    return render nothing: true, status: 500 if params[:swfurl] == ''
    render nothing: true, status: 200
  end

  def on_publish
    @user = User.find_by(streaming_key: params[:token])
    @user.update(total: 0)
    @user.update(live: true)
    render nothing: true, status: 200
  rescue
    render nothing: true, status: 500
  end

  def on_record_done
    @user = User.find_by(streaming_key: params[:token])
    @record = @user.records.create
    @record.update(uploaded: false, title: @user.title, total: @user.total)
    @user.update(live: false, total: 0)
    return if !File.exist?("/usr/local/nginx/html/screenshot/#{@user.nickname}.png")
    @record.copy_screenshot_to_tmp(params[:path])
    @record.delay.copy_video_to_tmp(params[:path])
    @record.delay.upload_to_s3(params[:path])
    # begin
      # File.delete("tmp/#{@user.nickname}.png")
      # File.delete("public/#{@user.uuid}_current.png")
    # rescue
      # puts 'tmp screenshot does not exist'
    # end
    if @user.private?
      @group = @user.groups.find_by(streaming: true)
      @record.delay.update(private: true, group_id: @group.id)
    end
    render nothing: true, status: 200
  end
end

app/views/stream/_all.html.erb
<section class="hero is-info">
  <div class="hero-content">
    <div class="container">
      <h2 class="subtitle"><%= "#{I18n.t('popular.video')}" %></h2>

      <% records.reverse.each_slice(3) do |record| %>
        <div class="columns">
          <% unless record[0].nil? %>
            <%= render partial: 'records/record', locals: { record: record[0], user: record[0].user } %>
          <% end %>
          <% unless record[1].nil? %>
            <%= render partial: 'records/record', locals: { record: record[1], user: record[1].user } %>
          <% end %>
          <% unless record[2].nil? %>
            <%= render partial: 'records/record', locals: { record: record[2], user: record[2].user } %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/stream/_chat.html.erb
<% chats.each do |chat| %>
  <li>
    <%= link_to stream_path(nickname: chat.sender), target: '_blank', style: 'color:#000;' do %>
      <article class="media">
        <figure class="media-left">
          <p class="image is-32x32">
            <%= image_tag "#{User.find_by(nickname: chat.sender).gh.image || User.find_by(nickname: chat.sender).twitter_image_url}", alt: chat.sender %>
          </p>
        </figure>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= User.find_by(nickname: chat.sender).name %></strong>
              <br>
              <%= chat.text %>
            </p>
          </div>
        </div>
      </article>
    <% end %>
  </li>
<% end %>

app/views/stream/_chat_form.html.erb
<div id="chat_form" style="position:fixed;width:100%;bottom:0px;height:32px;">
  <% if user_signed_in? %>
    <%= form_tag("/#{@user.nickname}/chat", remote: true, format: :js) do %>
      <%= text_field_tag 'chat[text]', :text, class: 'input message', placeholder: 'Message - Enter で送信', value: '', autofocus: true, style: 'margin-bottom: 10px;', required: false %>
    <% end %>
    <h2 class="subtitle msg-error" style="display:none;">Message can't be empty.</h2>
  <% else %>
    <%= link_to t('chat.signin'), new_user_session_path, class: 'button is-default', style: 'width: 100%;' %>
  <% end %>
</div>

app/views/stream/_player.html.erb
<video id="my-video" class="video-js" controls autoplay preload="auto" width="100%" height="auto" data-setup='{}'>
  <source src="http://<%= stream_url %>/live/<%= user.nickname %>.m3u8" type='application/x-mpegURL' />
  <source src="rtmp://<%= stream_url %>/live/<%= user.nickname %>" type='rtmp/mp4' />
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a web browser
    that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
  </p>
</video>
<script src="http://vjs.zencdn.net/5.9.2/video.js"></script>

app/views/stream/_thumbnail.html.slim
.column.is-3
  = link_to stream_path(nickname: user.nickname), target: '_blank' do
    .card
      .card-image
        figure.image.is-4by3
          = image_tag "/screenshot/#{user.gh.nickname}.png", alt: user.title
      .card-content
        .media
          .media-left
            figure.image.is-32x32= image_tag user.gh.image, alt: user.name
          .media-content
            p.title.is-5= user.name
            p.subtitle.is-6= user.nickname
          span.tag.is-dark style="float:right;"= category(user.category)
        .content
          p.subtitle.is-5= "#{user.title || I18n.t('content.title.default')}"
          - if user.records.count == 0
            small= "#{I18n.t('streaming.total')} : #{user.total}"
            br
          - else
            small= "#{I18n.t('streaming.total')} : #{user.total + user.records.map(&:total).inject(:+)}"

app/views/stream/all.html.slim
.container
  p style='margin-top:10px;'
  - if @users.count == 0
    h1.title= t('streaming.none')
  - else
    h1.title= t('streaming.now')
  - @users.each_slice(4) do |live_user|
    .columns
      - unless live_user[0].nil?
        = render partial: 'stream/thumbnail', locals: { user: live_user[0] }
      - unless live_user[1].nil?
        = render partial: 'stream/thumbnail', locals: { user: live_user[1] }
      - unless live_user[2].nil?
        = render partial: 'stream/thumbnail', locals: { user: live_user[2] }
      - unless live_user[3].nil?
        = render partial: 'stream/thumbnail', locals: { user: live_user[3] }
= render partial: 'all', locals: { records: Record.select { |r| r.duration.ceil > 0 } }

app/views/stream/chat.js.erb
$('#comments').html("<%= escape_javascript(render partial: 'chat', locals: { chats: @chats }) %>");

app/views/stream/extract_chat.html.erb
<!DOCTYPE html5>
<html>
  <head>
    <meta charset="UTF-8" />
    <title><%= @user.name %> - Chat</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'https://noraesae.github.io/perfect-scrollbar/perfect-scrollbar.min.css' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <!-- Nav -->
    <nav class="nav">
      <div class="nav-left">
        <span class="nav-item"><i class="fa fa-eye"></i><span id="current_number">0</span></span>
      </div>
    </nav>

    <!-- Header -->
    <div class="columns navbar" style="margin-bottom:0;">
      <div class="column is-12">
        <article class="media">
          <figure class="media-left">
            <p class="image is-64x64">
              <%= image_tag "#{@user.gh.image || @user.twitter_image_url}", alt: @user.name %>
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
              <span id="stream_title" style="font-size:18pt;"><%= @user.title || t('content.title.default') %></span>
                <br>
                <span style="font-size:14pt;"><%= @user.name %></span>
                <span class="tag is-dark" style="float:right;border-radius:0;"><%= category(@user.category) %></span>
              </p>
            </div>
          </div>
        </article>
      </div>
    </div>

    <!-- Comments -->
    <div id="comment_area" style='padding-top:0px;padding-bottom:0px;'>
      <ul id="comments" style='overflow-y:scroll;position:relative;height:100%;'>
        <%= render partial: 'chat', locals: { chats: @chats } %>
      </ul>
    </div>
    <%= render partial: 'stream/chat_form' %>

<script src='https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-beta1/jquery.min.js'></script>
<script src='https://s3-ap-northeast-1.amazonaws.com/pushould-static-files/v0.0.2/pushould.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/0.6.11/js/perfect-scrollbar.jquery.min.js'></script>
<script>
  $(function() {
    $('#comment_area').css('height', $(window).height() - $('nav').height() - $('.navbar').height() - 32 - 110 - 4);
    $('#comments').perfectScrollbar();
    $(window).resize(function() {
      $('#comment_area').css('height', $(window).height() - $('nav').height() - $('.navbar').height() - $('#chat_form').height());
      $('#comments').perfectScrollbar();
    });
    $('.message').keypress(function(e) {
      if (e.which == 13) {
        var _text = jQuery.trim($('.message').val());
        if (_text.length == 0) {
          $('.message').val('');
          $('.msg-error').show();
          return false;
        }
        $('.msg-error').hide();
        $('#comments').append('<% if user_signed_in? %><li>' +
          '<%= link_to stream_path(nickname: current_user.nickname), style: "color: #000", target: "_blank"  do %>' +
            '<article class="media">' +
              '<figure class="media-left">' +
                '<p class="image is-32x32">' +
                  '<%= image_tag User.find_by(nickname: current_user.nickname).gh.image, alt: current_user.name %>' +
                '</p>' +
              '</figure>' +
              '<div class="media-content">' +
                '<div class="content">' +
                  '<p>' +
                    '<strong><%= current_user.name %></strong>' +
                    '<br />' +
                    $('.message').val() +
                  '</p>' +
                '</div>' +
              '</div>' +
            '</article>' +
          '<% end %>' +
        '</li><% end %>');
//        $('#comments').animate({ scrollTop: $('#comments').prop('scrollHeight') }, "slow");
        $.ajax({
          type: 'POST',
          url: "/<%= @user.nickname %>/chat",
          data: {
            chat: {
              text: $('.message').val()
            }
          },
        });
        $('.message').val('');
        return false;
      }
    });
    $('#comments').animate({ scrollTop: $('#comments').prop('scrollHeight') }, "slow");
    var pushould = new Pushould({ url: '<%= @url %>', client_token: '<%= @client_token %>' });
    var channel = pushould.subscribe('<%= @channel %>');
    channel.bind('send', function(msg) {
      $('#comments').append('<li>' +
        '<a href="/' + msg.nickname + '" style="color: #000;" target="_blank">' +
          '<article class="media">' +
            '<figure class="media-left">' +
              '<p class="image is-32x32">' +
                '<img src=' + msg.image + ' alt=' + msg.name +' />' +
              '</p>' +
            '</figure>' +
            '<div class="media-content">' +
              '<div class="content">' +
                '<p>' +
                  '<strong>' + msg.name + '</strong>' +
                  '<br />' +
                  msg.text +
                '</p>' +
              '</div>' +
            '</div>' +
          '</article>' +
        '</a></li>');
      $('#comments').animate({ scrollTop: $('#comments').prop('scrollHeight') }, "slow");
    });
    channel.bind('current', function(msg) {
      $('#current_number').text(msg.count);
    });
    channel.bind('disconnect', function(msg) {
      $.ajax({
        type: 'POST',
        url: '/<%= @user.nickname %>/current'
      });
    });
    channel.bind('view', function(msg) {
      $('#total').text(msg.views);
    });
  });
</script>
  </body>
</html>