config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'

  ### OBS-Start
  # on_publish
  post 'on_publish' => 'stream#on_publish'

  # on_play
  post 'on_play' => 'stream#on_play'

  # on_record_done
  post 'on_record_done' => 'stream#on_record_done'

  # screenshot_done
  post 'screenshot_done' => 'stream#screenshot_done'
  ### OBS-End

  # Streams
  get 'streams' => 'stream#all'

  # Stream-User
  get ':nickname' => 'stream#user', as: :stream

  # Stream-Current
  post ':nickname/current' => 'stream#current'

  # Stream-Chat
  get ':nickname/chat_window' => 'stream#extract_chat', as: :extract_chat
  post ':nickname/chat' => 'stream#chat', as: :chat

  # User-Update-Description
  post ':nickname/update_description' => 'users#update_description', as: :update_description

  # User-Update-Title
  post ':nickname/update_title' => 'users#update_title', as: :update_title
  post 'profile/update' => 'users#update'
  post 'profile/category' => 'users#category'

  # User-Update-Record-Title
  post ':nickname/record/:uuid/update_title' => 'users#update_record_title', as: :update_record_title

  # User-Profile
  get ':nickname/profile' => 'users#profile', as: :profile

  # User-Play-Record
  get ':nickname/record/:uuid' => 'records#play', as: :play_record

  # User-Private-Stream
  get ':uuid/stream' => 'users#private_stream', as: :private_stream

  # User-Stop-Private-Stream
  get ':uuid/stop_stream' => 'users#stop_private_stream', as: :stop_private_stream

  # Record-Category
  post ':nickname/record/:uuid/category' => 'users#record_category'

  # Channel - Block
  resource :channel, only: [] do
    member do
      post :block
      post :unblock
    end
  end

  # Follow
  get ':nickname/follow' => 'users#follow', as: :follow

  # Unfollow
  get ':nickname/unfollow' => 'users#unfollow', as: :unfollow

  # Group
  post ':nickname/groups' => 'groups#create'

  # Group-Invite
  get '/groups/:uuid/invite/:user_uuid' => 'groups#invite', as: :group_invite

  # API
  namespace :api, format: :json do
    namespace :v1 do
      get 'me' => 'users#me'

      scope :videos do
        get '' => 'videos#all'
        get '/' => 'videos#all'
        get '/:nickname' => 'videos#user'
        get '/:nickname/:uuid' => 'videos#video'
        patch '/:nickname/:uuid/title' => 'videos#update'
        patch '/:nickname/:uuid/category' => 'videos#update'
      end

      scope :streams do
        get '' => 'streams#all'
        get '/:nickname' => 'streams#user'
        patch '/:nickname/title' => 'streams#update'
        get '/:nickname/comments' => 'streams#comments'
        # post '/:nickname/comments' => 'streams#create_comment'
        # get '/:nickname/block_list' => 'streams#block_list'
        # post '/:nickname/block' => 'streams#block'
        # post '/:nickname/unblock' => 'streams#unblock'
      end

      get '/:nickname/followings' => 'users#followings'
      get '/:nickname/followers' => 'users#followers'
    end
  end

  get '*path' => redirect('/')
end

app/views/layouts/_footer.html.slim
footer.footer
  .container
    .content.has-text-centered
      span.subtitle Dokugaku, Inc. All Rights Reserved.

app/views/layouts/_nav.html.slim
nav.nav
  .container
    .nav-left
      = link_to root_path, class: 'nav-item' do
        = image_tag asset_path('makerhub2x.png'), alt: 'logo'
      / = link_to streams_path, class: 'nav-item' do
        / span= t('streams')
    .nav-center= link_to 'Still in beta', '#', class: 'nav-item'
    span.nav-toggle
      span
      span
      span
    .nav-right.nav-menu
      span.nav-item
        - if user_signed_in?
          = link_to profile_path(nickname: current_user.nickname), class: 'button', target: '_blank'  do
            span= t('mypage')
        - else
          a.button.modal-button#signin_button data-target='#signin'= t('signin.title')
          .modal#signin
            .modal-background
            .modal-container
              .modal-content
                .box
                  article.media
                    .media-content
                      .content
                        = link_to user_github_omniauth_authorize_path, class: 'button is-default twitter' do
                          i style="margin-right:4px;" class="fa fa-github"
                          span= t('omniauth.github')
                        br /
                        span.subtitle style="color:#000;"= t('omniauth.notice')
            .modal-close

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="UTF-8"
    title= app_title(params)
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = stylesheet_link_tag    'nav', media: 'all', 'data-turbolinks-track' => false
    = stylesheet_link_tag 'http://vjs.zencdn.net/5.9.2/video-js.css', 'data-turbolinks-track' => false
    = javascript_include_tag 'application'
    = javascript_include_tag 'nav'
    = csrf_meta_tags
  body
    = render partial: 'layouts/nav'
    = yield
    = render partial: 'layouts/footer'